### ISSUE TITLE
White text and borders being changed to black

### ISSUE THREAD

**Issue by Rycochet** [guyonroche/exceljs#290]
Might be related to #261 

In Excel: change a cell colour to anything that it'll show up on, then change the text colour and border to (pure) white.

Saving from ExcelJS changes all the white text and border colours to black (I'd guess some default matching going on there). Other colours work normally.

Not checked against fill / patterns.

**Comment by guyonroche** [comment]
How Bizarre! I've reproduced this and the effects are weird.
I'll start looking into it straight away - apparently some colour management magic that I've missed.
Thanks for the heads up

**Comment by Rycochet** [comment]
Can confirm that you've fixed it in https://github.com/guyonroche/exceljs/commit/c51811abb2350ac63cde278dc7b76569c260f5ff - that looks painful!! Will leave this open till you push a release :-)

**Comment by guyonroche** [comment]
@Rycochet - I've just published 0.4.2 which should fix this (and the other) issues.
Turned out to be a combination of two things. First - I wasn't rendering theme="0" properly, and second - if you read one excel file, there's no guarantee that the default theme file used by ExcelJS is in any way compatable with the original. So I've added a workaround to copy the theme files
Could you check whether this resolves your issue?

**Comment by Rycochet** [comment]
Looks good :-)
