### ISSUE TITLE
workbook.addWorkSheet is not a function

### ISSUE THREAD

**Issue by Asaha5** [guyonroche/exceljs#472]
Below goes code I have written
```
'use strict';

const Hapi = require('hapi');
const Path = require('path');
var fs = require('fs');
var Excel = require('exceljs');

// create new server instance and connection information
const server = new Hapi.Server({  
    host: 'localhost',
    port: 5009
  })

//server.path(__dirname)

// Add the route
server.route({
    method: 'GET',
    path:'/path', 
    handler: function (request, h) {
        let file = 'test.xlsx';
        let filePath = Path.join(__dirname,file);
        return 'file path - '+filePath;
    }
});

server.route({
        method: 'GET',
        path: '/test.xlsx',
        handler: function (request, h) {
            let file = 'test.xlsx';
            let filePath = Path.join(__dirname,file)
            let contentType = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
            let data;
            console.log(filePath)
            fs.readFile(filePath, function(error, content) {
                data = content;
            });
            console.log(data);
            const res = h.response(data).type(contentType)
                .header('Content-Disposition', 'attachment; filename=' + file);
            
            console.log(res);
            return res;
        }
});
function createWorkBook(filePath) {
        console.log("Inside the function createWorkBook");
        var workbook = new Excel.Workbook();
        console.log(workbook);
        workbook.views = [
            {
              x: 0, y: 0, width: 10000, height: 20000,
              firstSheet: 0, activeTab: 1, visibility: 'visible'
            }
        ]
        var worksheet = workbook.addWorkSheet("Data",{properties:{tabColor:{argb:'FFC0000'}}});
       
        workbook.xlsx.writeFile(filePath)
                .then(function() {
                    console.log("File created successfully")
                });
}
        

// Start the server
async function start() {

    try {
        await server.start();
    }
    catch (err) {
        console.log(err);
        process.exit(1);
    }

    console.log('Server running at:', server.info.uri);
};

start();
createWorkBook(Path.join(__dirname,'data.xlsx'));
```

Below goes the error:

        var worksheet = workbook.addWorkSheet("Fund Data",{properties:{tabColor:{argb:'FFC0000'}}});
                                 ^

TypeError: workbook.addWorkSheet is not a function
    at createWorkBook (C:\Work\FMS\src\core\server\hapiServer.js:82:34)
    at Object.<anonymous> (C:\Work\FMS\src\core\server\hapiServer.js:131:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

Any help on this?

**Comment by Asaha5** [comment]
Solved it.

**Comment by helixquar** [comment]
How did you solve it?

**Comment by AsharDweedar** [comment]
How ?

**Comment by Meenakshisundaram23** [comment]
Please tell how you solved it? I have a same error now.

**Comment by papb** [comment]
The casing is wrong, it is `addWorksheet`, not `addWorkSheet`. See [the readme](https://github.com/exceljs/exceljs#add-a-worksheet).

**Comment by Meenakshisundaram23** [comment]
I got the same error, when I tried with correct case, please find the below code.

this.createsheet = async function (workbook, sheetname) {
        try {
            worksheet = await workbook.addWorksheet(sheetname);
            return worksheet
        }
        catch (err) {
            console.log('Error Message - ', err);
        }
    }

**Comment by papb** [comment]
@Meenakshisundaram23 please format the code in your posts, see [Mastering Markdown](https://guides.github.com/features/mastering-markdown/)

**Comment by digable1** [comment]
This is probably a different issue, same response (since it's years later):  I'm getting this error.

1.  This is with Typescript - where I start with type 'unknown' and then coerce it to type 'any'.
2.  The first spreadsheet I create works just fine.
3.  The second spreadsheet now gives me this error.

Note:  I'm not using streaming as these spreadsheets are quite small.  So if I'm reading the doc correctly, I don't have to do any commit calls when I create and write the first spreadsheet.

And I start the second spreadsheet out with 'const workbook = new ExcelJS.Workbook();' (same as the first one, as the method/function is shared).

I've done a 'console.log((workbook as any).addWorksheet' and for good measure logged getWorksheet:  For the first spreadsheet, I get the function listed as you'd expect.  For the second one, it's undefined for both functions/methods.

Do I need to do a worksheet.commit() or workbook.commit() before a do an xlsx.write(...) on the first spreadsheet?

**Comment by papb** [comment]
> The second spreadsheet I'm trying to create now gives me this error (TypeError: workbook.addWorksheet is not a function).

This is unlikely to be related to whether or not you make `.commit()` calls or whatever in the middle. Can you post a larger part of your code?

**Comment by digable1** [comment]
I can - may take a while to figure out what the threshold is of getting this error (will have to make time for it at work).

However:  My next step is leverage the ts definition file I found in the code, and add an import { Workbook } from exceljs - and see if that exposes anything with stronger typing.  If I still get this type of behavior, I'll work on something that can demonstrate what I'm encountering.

So never mind my comment about a .dts file - you've got one. However, I would like to replace the question with "can you document the typescript import" instead of the requireJS(...)?

**Comment by digable1** [comment]
Update:  While I haven't tested it yet and am about to - I'm pretty confident I know what happened.  In a nutshell:  Operator error.

In a further summary:  Lesson for today - when you are so used to Typescript catching the idiotic stuff instead of linting Javascript, quit being really get lazy and forgetting to check basic things.  Such as:

1. Calling spliceRow instead of spliceRows.
2. Forgetting to put an await in calling an async function in one of the few lines of code that are different between constructing the first spreadsheet and the second one.  So of course this fat finger was in the constructing the second one.

Bottom line:  Never mind.
