### ISSUE TITLE
Do we support Excel to JSON and vice versa

### ISSUE THREAD

**Issue by murliatdure** [guyonroche/exceljs#8]

**Comment by guyonroche** [comment]
Yes it does.

var workbook = createAndFillWorkbook();
var json = JSON.stringify(workbook.model);

var workbook2 = new Excel.Workbook();
workbook2.model = JSON.parse(json);

**Comment by kalyanmantri** [comment]
That didn't work for me with latest version of exceljs

**Comment by Siemienik** [comment]
works:
![image](https://user-images.githubusercontent.com/2893099/74479219-12ceaf80-4eaf-11ea-9fbe-d7520cb77c4c.png)

**Comment by kalyanmantri** [comment]
@Siemienik Thanks for replying. The way you did it worked for me, I am looking for something like..

var myModel: WorkbookModel = {
     sheets: [...],
     properties: {...}
 }
var workbook = new Excel.Workbook();
workbook.model = myModel;

**Comment by Siemienik** [comment]
it should works, for more details what should be placed inside `myModel` see this :
https://github.com/exceljs/exceljs/blob/master/index.d.ts#L1422

if something went wrong, please study source code liable about applying the workbook model:
https://github.com/exceljs/exceljs/blob/master/lib/doc/workbook.js#L179

**Comment by jagabs** [comment]
im getting this SyntaxError: Unexpected token c in JSON at position 1
    at JSON.parse  where parsing the model

**Comment by jagabs** [comment]
ERROR Error: Uncaught (in promise): TypeError: e.toISOString is not a function
TypeError: e.toISOString is not a function
    at r.d.DateFormat [as _format]

    "exceljs": "^1.15.0",

**Comment by andreshincapier** [comment]
This information could be useful for others. When I tried to create a workbook from JSON, I encountered an error. However, the error was resolved when I checked the values. This is because some values are required for the constructor. Make sure your JSON has all the necessary values

`{
  "creator": "Someone",
  "lastModifiedBy": "Someone else",
  "created": "2024-03-25T03:27:36.011Z",
  "modified": "2024-03-25T03:27:36.011Z",
  "properties": {},
  "worksheets": [],
  "sheets": [],
  "definedNames": [],
  "views": [],
  "company": "",
  "manager": "",
  "title": "",
  "subject": "",
  "keywords": "",
  "category": "",
  "description": "",
  "media": [],
  "calcProperties": {}
}
`
